version: '3'

services: 
  core:
    build: ./server
    image: core:latest
    volumes: 
      - sql_scripts:/server/sql-files

  database:
    image: mysql:5.7
    restart: always
    volumes: 
      - sql_scripts:/docker-entrypoint-initdb.d
      - server_db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: ragnarok
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
      MYSQL_ROOT_PASSWORD: secret
    depends_on: 
      - core
    ports:
      - 3306:3306

  map:
    image: core
    restart: always
    command: ./wait.sh database:3306 -- "./map-server"
    depends_on: 
      - core
      - database
    ports:
      - 5121:5121

  login:
    image: core
    restart: always
    command: ./wait.sh database:3306 -- "./login-server"
    depends_on: 
      - core
      - database
    ports:
      - 6900:6900

  char:
    image: core
    restart: always
    command: ./wait.sh database:3306 -- "./char-server"
    depends_on: 
      - core
      - database
    ports: 
      - 6121:6121

  flux:
    image: richarvey/nginx-php-fpm:latest
    restart: always
    environment:
      GIT_EMAIL: bryan@avalonstar.com
      GIT_NAME: Bryan Veloso
      GIT_REPO: https://github.com/bryanveloso/FluxCP/
      GIT_BRANCH: dockerize
      DOMAIN: renova.avalonstar.tv
    ports:
      - 80:80
      - 443:443

volumes: 
  sql_scripts:
  server_db:
